### PR TITLE
Update Listen gem to latest version

### PR DESCRIPTION
**Pull request by jkowens**
I noticed there was a ThreadError being throw on system exit using Ruby 2.0. A fix for that is included.

### CODE REVIEW

**Comment by jkowens** [comment]
I'm not sure what is going on with the tests. Any ideas?

**Comment by MicahChalmer** [comment]
Looks like the problem with the tests is minitest 4 vs minitest 5.  It has to do with using both an `around` method in the base class and a `before` block in the test itself.  In minitest 4, the `before` block runs first, then the `around` method.  In minitest 5, the `around` runs first, with the `before` block being called at the `yield.`  The tests in mr-sparkle depend on setting a variable in a `before` block and using it in the `around` block, so it breaks in minitest 5.

The temporary fix will be to lock it down to minitest 4 in the gemspec...that should allow this to be merged.  The tests should be redone not to depend on this though...but that's for when I have more time to do it (or if someone else is kind enough to take care of it and send in a pull request.)

**Comment by MicahChalmer** [comment]
I checked in the temporary fix, which makes the tests pass on master after a `bundle update`.  If I merge in this PR, a couple of tests fail in ways that look legitimate ("recovers if the app becomes unstartable" and "reloads the entire app, including gems, when Gemfile is changed").

**Comment by jkowens** [comment]
Cool, thanks for looking into this. If I get some more time, and can figure out how these tests work...maybe I could try helping with the update :)

**Comment by jkowens** [comment]
Due to some changes in the way Listen works, I think `--full-reload-pattern` has to match a subset of `--pattern`. Do you see an issue with this?

**Comment by jkowens** [comment]
So I found that I could create a union of the two regex patterns to maintain existing behavior. It's amazing what you find when you read the docs :)

**Comment by MicahChalmer** [comment]
Merged.  Thanks!

**Pull request merged**
